source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYCoreFramework_Example', :exclusive => true do
  pod 'HYCoreFramework', :path => '../'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.10'
end

target 'HYCoreFramework_Tests', :exclusive => true do
  pod 'HYCoreFramework', :path => '../'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.10'
  
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
