
target 'HYCoreFramework_Example', :exclusive => true do
  pod 'HYCoreFramework', :path => '../'
end

target 'HYCoreFramework_Tests', :exclusive => true do
  pod 'HYCoreFramework', :path => '../'
end
